import React, { ReactNode } from 'react';
import Head from 'next/head';
import styles from '@/styles/layout/Layout.module.scss';

type Props = {
  children: ReactNode;
};

const Layout: React.FC<Props> = props => (
  <main className={styles.main}>
    <Head>
      <title>GIFcentration 2</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    {props.children}
  </main>
);

export default Layout;
