import React, { ReactNode } from 'react';
import Head from 'next/head';
import Header from './Header';
import Footer from './Footer';

type Props = {
  children: ReactNode;
};

const Layout: React.FC<Props> = props => (
  <>
    <Head>
      <title>GIFcentration 2</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    <main>{props.children}</main>
    <Footer />
  </>
);

export default Layout;
