import { Metadata } from 'next';
import Home from './home';
import { ReactElement } from 'react';

export const metadata: Metadata = {
  title: 'GIFcentration 2',
  description: 'Generated by create next app',
};

export default async function Page(): Promise<ReactElement> {
  return <Home />;
}
